"""Abstract ModelProvider interface and schema definitions for LLM integrations.

This module defines the core abstraction layer for infrastructure-agnostic model providers,
enabling uniform interaction with diverse LLM endpoints (e.g., OpenAI, Gemini, Ollama)
via standard synchronous, streaming, info, and health-checking interfaces.
"""

from abc import ABC, abstractmethod
from collections.abc import AsyncGenerator
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field


class MessageRole(StrEnum):
    """Enumeration of standard chat message roles."""

    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"


class ModelCapability(StrEnum):
    """Enumeration of feature capabilities supported by LLM endpoints."""

    TEXT_GENERATION = "text_generation"
    STREAMING = "streaming"
    FUNCTION_CALLING = "function_calling"
    STRUCTURED_OUTPUT = "structured_output"
    VISION = "vision"
    EMBEDDINGS = "embeddings"


class ModelConfig(BaseModel):
    """Dynamic runtime execution configuration for a model provider instance.

    Attributes:
        provider_id (str): Identifier of target provider adapter (e.g., openai, gemini, anthropic, custom).
        model_name (str): Target model identifier string (e.g., gpt-4o, gemini-1.5-pro, llama-3-70b).
        temperature (float): Sampling temperature value between 0.0 and 2.0.
        max_tokens (int | None): Optional upper bound on generated completion tokens.
        system_prompt (str | None): Optional system prompt instructions.
        base_url (str | None): Optional custom HTTP base URL for local/private endpoints.
        api_key (str | None): Optional client-provided API key.
        provider_params (dict[str, Any]): Arbitrary provider-specific keyword parameters.
    """

    provider_id: str = Field(default="openai", description="Target provider adapter identifier")
    model_name: str = Field(default="gpt-4o", description="Target model version identifier")
    temperature: float = Field(default=0.7, ge=0.0, le=2.0, description="Sampling temperature")
    max_tokens: int | None = Field(default=None, description="Max completion token limit")
    system_prompt: str | None = Field(default=None, description="System prompt instructions")
    base_url: str | None = Field(default=None, description="Custom HTTP base URL endpoint")
    api_key: str | None = Field(default=None, description="Client API key secret override")
    provider_params: dict[str, Any] = Field(
        default_factory=dict, description="Arbitrary provider extension parameters"
    )


class ChatMessage(BaseModel):
    """Data model representing a single chat message payload.

    Attributes:
        role (MessageRole): Role of the message author (system, user, assistant, tool).
        content (str): Textual content of the message.
        name (str | None): Optional identifier name for tool or user attribution.
    """

    role: MessageRole = Field(description="Role of the message author")
    content: str = Field(description="Textual content of the chat message")
    name: str | None = Field(default=None, description="Optional author or tool name identifier")


class TokenUsage(BaseModel):
    """Data model tracking token consumption for an LLM generation.

    Attributes:
        prompt_tokens (int): Number of tokens in the input prompt.
        completion_tokens (int): Number of tokens in the generated response.
        total_tokens (int): Combined count of prompt and completion tokens.
    """

    prompt_tokens: int = Field(default=0, description="Input prompt token count")
    completion_tokens: int = Field(default=0, description="Generated response token count")
    total_tokens: int = Field(default=0, description="Total consumed token count")


class ModelResponse(BaseModel):
    """Data model representing a complete generation response from a model provider.

    Attributes:
        content (str): The complete text generated by the model.
        model_name (str): Identifier of the specific model used for generation.
        usage (TokenUsage): Token usage statistics for the request.
        finish_reason (str | None): Reason for completion (e.g., stop, length, content_filter).
        raw_response (dict[str, Any] | None): Optional raw response payload from the underlying provider.
    """

    content: str = Field(description="Complete generated text response")
    model_name: str = Field(description="Identifier of the model used")
    usage: TokenUsage = Field(default_factory=TokenUsage, description="Token consumption metrics")
    finish_reason: str | None = Field(default="stop", description="Completion termination reason")
    raw_response: dict[str, Any] | None = Field(default=None, description="Raw provider payload")


class ModelResponseChunk(BaseModel):
    """Data model representing a single streamed delta chunk from a model provider.

    Attributes:
        delta_content (str): The incremental text chunk generated in this stream step.
        finish_reason (str | None): Optional completion termination reason if stream ended.
    """

    delta_content: str = Field(description="Incremental generated text chunk")
    finish_reason: str | None = Field(default=None, description="Optional stream end reason")


class ModelInfo(BaseModel):
    """Data model describing capabilities and specifications of a model provider.

    Attributes:
        provider_name (str): Canonical name of the model provider (e.g., openai, gemini, ollama).
        model_name (str): Specific model identifier version.
        context_window (int): Maximum token context window supported by the model.
        max_output_tokens (int): Maximum output token limit for a single completion.
        supports_streaming (bool): Flag indicating if token streaming is supported.
        supports_tools (bool): Flag indicating if native tool/function calling is supported.
    """

    provider_name: str = Field(description="Canonical provider identifier")
    model_name: str = Field(description="Model version identifier")
    context_window: int = Field(default=128000, description="Maximum context window size in tokens")
    max_output_tokens: int = Field(default=4096, description="Maximum completion token limit")
    supports_streaming: bool = Field(default=True, description="Supports real-time token streaming")
    supports_tools: bool = Field(default=True, description="Supports native tool/function calling")


class ProviderHealth(BaseModel):
    """Data model indicating health status and connectivity of a model provider.

    Attributes:
        is_healthy (bool): Flag indicating if the model endpoint is responsive and healthy.
        latency_ms (float): Response latency measurement in milliseconds.
        details (dict[str, Any]): Additional health metadata or diagnostic error information.
    """

    is_healthy: bool = Field(description="Endpoint health status indicator")
    latency_ms: float = Field(default=0.0, description="Ping/health check latency in milliseconds")
    details: dict[str, Any] = Field(default_factory=dict, description="Diagnostic health metadata")


class ModelProvider(ABC):
    """Abstract base class defining the standardized contract for all LLM providers.

    All concrete model provider integrations (e.g., OpenAI, Gemini, Anthropic, Ollama)
    must inherit from this interface and implement its abstract methods.
    """

    @abstractmethod
    async def generate(
        self,
        messages: list[ChatMessage],
        temperature: float = 0.7,
        max_tokens: int | None = None,
        system_instruction: str | None = None,
        **kwargs: Any,
    ) -> ModelResponse:
        """Generates a complete textual response from the model provider.

        Args:
            messages (list[ChatMessage]): List of conversation history messages.
            temperature (float, optional): Sampling temperature between 0.0 and 2.0. Defaults to 0.7.
            max_tokens (int | None, optional): Upper bound on generated response tokens. Defaults to None.
            system_instruction (str | None, optional): Optional system prompt instructions. Defaults to None.
            **kwargs (Any): Additional provider-specific keyword arguments.

        Returns:
            ModelResponse: Standardized response object containing content and metadata.

        Raises:
            ProviderError: If the underlying model endpoint fails or returns an error.
            ValidationError: If input parameters or messages fail schema validation.
        """
        pass

    @abstractmethod
    def stream(
        self,
        messages: list[ChatMessage],
        temperature: float = 0.7,
        max_tokens: int | None = None,
        system_instruction: str | None = None,
        **kwargs: Any,
    ) -> AsyncGenerator[ModelResponseChunk, None]:
        """Streams real-time delta response chunks from the model provider.

        Args:
            messages (list[ChatMessage]): List of conversation history messages.
            temperature (float, optional): Sampling temperature between 0.0 and 2.0. Defaults to 0.7.
            max_tokens (int | None, optional): Upper bound on generated response tokens. Defaults to None.
            system_instruction (str | None, optional): Optional system prompt instructions. Defaults to None.
            **kwargs (Any): Additional provider-specific keyword arguments.

        Yields:
            ModelResponseChunk: Real-time incremental delta text chunk.

        Raises:
            ProviderError: If the streaming connection fails or disconnects prematurely.
        """
        pass

    @abstractmethod
    def get_model_info(self) -> ModelInfo:
        """Returns metadata and specifications for the underlying model.

        Returns:
            ModelInfo: Standardized model specification object.
        """
        pass

    @abstractmethod
    async def list_models(self) -> list[str]:
        """Lists available models exposed by the target provider endpoint.

        Returns:
            list[str]: List of model string identifiers.
        """
        pass

    @abstractmethod
    async def health(self) -> ProviderHealth:
        """Performs a health check against the provider endpoint to measure latency and availability.

        Returns:
            ProviderHealth: Standardized provider health status object.
        """
        pass
