"""create conversation_sessions and session_messages tables

Revision ID: f24c7cfd26f8
Revises:
Create Date: 2026-09-26 14:36:57.248580

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "f24c7cfd26f8"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
